version: '3'

services:
    app:
        build: .
        environment:
            - DB_URI=mongodb://mongo/api
        ports:
            - 1337:1337
        restart: always

    mongo:
        image: mongo
        volumes:
            - dbdata:/data/db
        ports:
            - 27017:27017
        restart: always

volumes:
    dbdata:
